version: '3'
services:
    r-udf-child-service:
        build: .
        image: openeor/r-udf-base:0.3.0
        container_name: r-udf-custom
        environment:
            - PLUMBER_PORT=5555
        volumes:
            - libraries.json:/opt/openeo-r-udf/libraries.json
        ports:
            - "5555:5555"
